#-------------------------------------------------------------------#
#------------------------------- Misc ------------------------------#
#-------------------------------------------------------------------#
seed: 0
dataset: xx


#-------------------------------------------------------------------#
#----------------------------- Trainer -----------------------------#
#-------------------------------------------------------------------#
trainer:
  type: xx
  optim:
    epoch: xx
    something_else: xx
    lr: 1.6e-04
    lr_final: 1.6e-06
    scale_factor: 0.1

  loss:
    main_loss:
      w: 0.1
      something_else: xx
    else_loss:
      w: 0.1
      something_else: xx

  general_ctrl_cfg:

